# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ManUNews' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ManUNews
  pod 'CVCalendar', '~> 1.4.1'
  pod 'SnapKit', '~> 3.0'
  pod 'RxSwift', '~> 3.0'
  pod 'RxCocoa'
  pod 'Moya', '8.0.0-beta.4'
  pod 'Moya-ModelMapper', '4.0.0-beta.3'
  pod 'Moya-ModelMapper/RxSwift', '4.0.0-beta.3'
  pod 'RxOptional'

end
